/**
 * Credits and licences.
 *
 * The honest summary: one third-party library, and everything else — every
 * texture, every sound — is generated by code in this repository. That is why
 * the whole game is a few hundred kilobytes and works offline.
 */

export const CREDITS_HTML = `
  <div class="credit-block">
    <h3>Third-party code</h3>
    <table class="credit-table">
      <thead><tr><th>Asset</th><th>Creator</th><th>Licence</th><th>Source</th></tr></thead>
      <tbody>
        <tr>
          <td><strong>three.js</strong> r169 (<code>src/vendor/three.module.js</code>)</td>
          <td>Ricardo Cabello (mrdoob) and the three.js contributors</td>
          <td>MIT — full text in <code>src/vendor/three.LICENSE</code></td>
          <td><a href="https://github.com/mrdoob/three.js" target="_blank" rel="noopener">github.com/mrdoob/three.js</a></td>
        </tr>
      </tbody>
    </table>
    <p class="tiny">This is the only external dependency, and it is bundled locally so the game never needs the network.</p>
  </div>

  <div class="credit-block">
    <h3>Artwork — textures and models</h3>
    <table class="credit-table">
      <thead><tr><th>Asset</th><th>Creator</th><th>Licence</th><th>How it is made</th></tr></thead>
      <tbody>
        <tr><td>Runway, taxiway and apron surfaces, painted markings, runway numbers</td><td>Island Flight Simulator project</td><td>CC0 1.0 (public domain)</td><td>Canvas 2D + value noise — <code>src/render/textures.js</code></td></tr>
        <tr><td>Grass, sand, rock, terrain blending</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Fractal value noise, per-vertex blend weights</td></tr>
        <tr><td>Ocean surface and foam</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Height-field → normal-map conversion</td></tr>
        <tr><td>Aircraft paint, panel lines, rivets, registration</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Canvas 2D</td></tr>
        <tr><td>Instrument panel, all eight instruments, radio stack</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Drawn live to a canvas — <code>src/aircraft/cockpit.js</code></td></tr>
        <tr><td>Buildings, hangars, rooftops, palms</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Canvas 2D + instanced primitives</td></tr>
        <tr><td>Clouds, rain, windscreen droplets</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Fractal noise sprites + custom shaders</td></tr>
        <tr><td>Aeroplane, cockpit, airfield and island geometry</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Lofted aerofoils and primitives built in code — no model files</td></tr>
      </tbody>
    </table>
  </div>

  <div class="credit-block">
    <h3>Sound</h3>
    <table class="credit-table">
      <thead><tr><th>Asset</th><th>Creator</th><th>Licence</th><th>How it is made</th></tr></thead>
      <tbody>
        <tr><td>Engine start, idle, acceleration, propeller</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Periodic-wave firing tone + blade-slap LFO + combustion noise, all tied to rpm</td></tr>
        <tr><td>Slipstream and airframe whistle</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Pink noise through speed-driven band-pass filters</td></tr>
        <tr><td>Rain, thunder</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Filtered noise with envelopes</td></tr>
        <tr><td>Tyres, touchdown chirp, landing gear, flaps</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Noise bursts, swept oscillators, hydraulic motor synthesis</td></tr>
        <tr><td>Stall warner, gear horn, terrain and overspeed alerts, chimes</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Oscillators with tremolo</td></tr>
        <tr><td>ATC radio: relay clicks, squelch, static, heterodyne interference, dropouts, indistinct voice</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Three-formant resonator model driven by a syllable rhythm taken from the message text — <code>src/audio/atc.js</code></td></tr>
        <tr><td>Ambient music</td><td>Island Flight Simulator project</td><td>CC0 1.0</td><td>Detuned triangle pad, four-chord progression</td></tr>
      </tbody>
    </table>
    <p class="note">
      <strong>About the radio voices.</strong> <strong>By default</strong> there is no text-to-speech and no
      AI-generated voice anywhere in this game, and no voice recordings are bundled. The radio calls are
      indistinct formant-filtered chatter — the acoustic shape of speech without any words — pushed through a
      realistic radio chain, with the actual words delivered as on-screen subtitles.
      <br><br>
      <strong>Settings &rarr; Sound &rarr; ATC voices</strong> lets you change that if you would rather.
      <em>Your device&rsquo;s speech voice</em> uses your operating system&rsquo;s own speech synthesiser —
      that option <em>is</em> text-to-speech, which is exactly why it is opt-in and not the default; nothing is
      generated by a model and nothing is downloaded. <em>Recordings I have added myself</em> plays clips you
      supply in <code>assets/atc/</code>; the game ships with none. See <code>assets/atc/README.md</code> for
      the manifest format and for which licences are safe to redistribute — please credit everything you add.
      </p>
  </div>

  <div class="credit-block">
    <h3>References used while building the flight model</h3>
    <ul class="credit-list">
      <li><strong>FAA Airplane Flying Handbook (FAA-H-8083-3)</strong> — take-off, crosswind landing and traffic-pattern procedures. Work of the U.S. Government, public domain. <a href="https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/airplane_handbook" target="_blank" rel="noopener">faa.gov</a></li>
      <li><strong>FAA Pilot's Handbook of Aeronautical Knowledge (FAA-H-8083-25)</strong> — aerodynamics, PAPI indications, weather. Public domain. <a href="https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak" target="_blank" rel="noopener">faa.gov</a></li>
      <li>Aerodynamic coefficients are typical published values for a four-seat single-engine trainer, tuned by hand for playability.</li>
    </ul>
  </div>

  <div class="credit-block">
    <h3>Typography</h3>
    <p>System font stack only (<code>-apple-system, Segoe UI, Roboto, Helvetica, Arial</code>). No web fonts are downloaded, so text renders instantly and offline.</p>
  </div>

  <div class="credit-block">
    <h3>This game</h3>
    <p>Island Flight Simulator — code and generated assets released under <strong>CC0 1.0</strong> (public domain).
    You may copy it, change it, share it and use it in your own projects. The bundled three.js library stays
    under its own MIT licence.</p>
  </div>
`;
